export let objto = {
    casa: 1,
    barrio: 15
}

export let arrayss = [1,2,3,4,5,6,7,8,9];
/* PRUEBA */
/* LA ETIQUETA HEAD SIRVE PARA HACER LA CONEXION CON EL NAVEGADOR Y COMUNICARNOS CON EL */
/* LA DIFERENCIA ES QUE EL HEAD ES CONSTRUIDO PARA EL NAVEGADOR Y EL BODY PARA LA PAGINA  */
/* SE CREA EL DOCUMENTO HTML DENTRO DE LA ESTRUCTURA BASICA EN EL BODY USAMOS LA ETIQUETA IMG Y PASAMOS LA DIRECCION DE DONDE SE ENCUANTRA LA IMAGEN EN EL SRC */
/* SE CREA EL DOCUMENTO HTML DENTRO DE LA ESTRUCTURA BASICA EN EL BODY USAMOS LA ETIQUETA VIDEO Y PASAMOS LA DIRECCION DE DONDE SE ENCUANTRA el video  EN EL SRC */
/* SIRVE PARA CONECTAR OTRA PAGINA DE HTML A LA ACTUAL */
/* SE CREA EL DOCUMENTO HTML DENTRO DE LA ESTRUCTURA BASICA EN EL BODY USAMOS LA ETIQUETA FORM LUEGO USAMOS LA ETIQUETA LENGED PARA COLOCAR EL TITULO YA DENTRO DE ESTE PODEMOS COLOCAR LOS INPUT Y BUTTON QUE NECESITEMOS  */
/*RESETEA LA PAGINA */
/* EL HR ES PARA HACER UN SALTO DE LINEA Y EL BR DA UN SALTO DE LINEA Y COLOCA  UNA LINEA Y INFORMA AL NEVAGOR QUE EL SIGUIENTE CONTENIDO ES DIFERENTE AL ANTERIOR */
/* ES LA ETIQUETA DIV */
/*  HEADER MAIN FOOTER */
/* LA UL GENERA UNA LISTA DESORDENADA Y LA OL UNA ORDENADA */
/* CON LA ETIQUETA I */
/* CON LA ETIQUETA a Y PONEMOS LA DIRRECCION DONDE QUEREMOS IR EN EL href */
 
/* CON LA PROPIEDAD target y dentro de esta el valor _blank*/
/* la clase es retulisable y el id no 
la especifidad es diferente
la especifidad del id es superior */

/* el id con id="nombreUnico"
clase con class="nombreClase" */

/* color
con la priedad color:
font-family */

/* bgc */

/* colocandole fielset en el display  */
